[profile.default]
src = "contracts/reconstructed"
out = "out"
libs = ["lib"]
solc = "bin/solc/solc-0.4.18"
solc_version = "0.4.18"
auto_detect_solc = false
optimizer = false
evm_version = "byzantium"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
